# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190524_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, editable=False, verbose_name='Html内容'),
        ),
    ]
